scoreboard objectives add cursemark dummy
scoreboard objectives add cursemarkactive dummy
scoreboard objectives add cursemarkcd dummy
scoreboard objectives add dynamic dummy
scoreboard objectives add dynamicattack dummy
scoreboard objectives add gatestime dummy
scoreboard objectives add eightgates dummy
scoreboard objectives add gatesactive dummy
scoreboard objectives add fleeting dummy
scoreboard objectives add hundredhealings dummy
scoreboard objectives add hundredhealingsactive dummy
scoreboard objectives add leafwhirl dummy
scoreboard objectives add sagechakra dummy
scoreboard objectives add sagemode dummy
scoreboard objectives add shadowclone dummy
scoreboard objectives add substitution dummy
scoreboard objectives add summon dummy
scoreboard objectives add teleport dummy
scoreboard objectives add transformation dummy